# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 07:30
from __future__ import unicode_literals

import actors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actor',
            name='photo',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=actors.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='actor',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
